export const AP_LOCATION_CATALOG: Record<string,string[]> = {
  'Amalapuram': ['Government Degree College, Amalapuram','Other institution'],
  'Anakapalle': ['Government College for Women, Anakapalle','Other institution'],
  'Anantapur': ['Sri Krishnadevaraya University','Jawaharlal Nehru Technological University Anantapur (JNTUA)','Government Arts College, Anantapur','Other institution'],
  'Bapatla': ['Bapatla Engineering College','Other institution'],
  'Bhimavaram': ['D.N.R. College, Bhimavaram','Other institution'],
  'Chittoor': ['Sri Venkateswara Veterinary University','Other institution'],
  'Eluru': ['Sir C.R. Reddy College','Other institution'],
  'Guntur': ['Acharya Nagarjuna University','KLEF (KL University)','Vignan’s Foundation for Science, Technology & Research','Government College for Women, Guntur','Other institution'],
  'Hindupur': ['Government Degree College, Hindupur','Other institution'],
  'Kadapa': ['Yogi Vemana University','Government College for Men, Kadapa','Other institution'],
  'Kakinada': ['Jawaharlal Nehru Technological University Kakinada (JNTUK)','Ideal College of Arts and Sciences','Other institution'],
  'Kurnool': ['Rayalaseema University','Indian Institute of Information Technology, Design and Manufacturing Kurnool (IIITDM Kurnool)','Dr. Abdul Haq Urdu University','Other institution'],
  'Machilipatnam': ['Krishna University','D.N.R. College, Machilipatnam','Other institution'],
  'Nandyal': ['Government Degree College, Nandyal','Other institution'],
  'Narasaraopet': ['Government College, Narasaraopet','Other institution'],
  'Nellore': ['Vikrama Simhapuri University','Government College, Nellore','Other institution'],
  'Ongole': ['Government College for Men, Ongole','Other institution'],
  'Paderu': ['Government Degree College, Paderu','Other institution'],
  'Parvathipuram': ['Government Degree College, Parvathipuram','Other institution'],
  'Proddatur': ['Y.S.R. Engineering College of YVU','Other institution'],
  'Puttaparthi': ['Sri Sathya Sai Institute of Higher Learning','Other institution'],
  'Rajamahendravaram': ['Adikavi Nannaya University','Government College (Autonomous), Rajamahendravaram','Other institution'],
  'Rayachoti': ['Government Degree College, Rayachoti','Other institution'],
  'Srikakulam': ['Dr. B.R. Ambedkar University, Srikakulam','Government College (Autonomous), Srikakulam','Other institution'],
  'Tenali': ['V.S.R. & N.V.R. College','Other institution'],
  'Tirupati': ['Sri Venkateswara University','Sri Padmavati Mahila Visvavidyalayam','Indian Institute of Science Education and Research Tirupati (IISER Tirupati)','Indian Institute of Technology Tirupati (IIT Tirupati)','Sri Venkateswara Institute of Medical Sciences (SVIMS)','Other institution'],
  'Vijayawada': ['Andhra Loyola College','Velagapudi Ramakrishna Siddhartha Engineering College','Other institution'],
  'Visakhapatnam': ['Andhra University','GITAM University','Indian Institute of Management Visakhapatnam','Andhra Medical College','Other institution'],
  'Vizianagaram': ['Jawaharlal Nehru Technological University Gurajada Vizianagaram (JNTUGV)','Government College (Autonomous), Vizianagaram','Other institution'],
};
export const AP_CITIES = Object.keys(AP_LOCATION_CATALOG).sort((a,b)=>a.localeCompare(b));
