-- The base schema already contains the nullable Transaction.reference column and its index.
-- This migration is intentionally a no-op so the historical migration remains
-- compatible with the reconstructed initial schema.
